#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#yaml faire attention au tab ==> langage non permissif
controllers:
  resource: ../src/Controller
  type: annotation